# Generated by Django 3.1.4 on 2021-02-13 17:36

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.CharField(help_text='Informe as características do imóvel', max_length=35, verbose_name='Caracteristicas')),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=35, verbose_name='Nome')),
                ('celular', models.CharField(help_text='Informe o telefone Ex.:(xx)xxxxx-xxxx', max_length=14, verbose_name='Celular')),
                ('email', models.EmailField(help_text='Informe o email', max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Comodidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodidades', models.CharField(help_text='Informe as comodidades do imóvel', max_length=35, verbose_name='Comodidades')),
            ],
            options={
                'verbose_name': 'Comodidade',
                'verbose_name_plural': 'Comodidades',
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=35, verbose_name='Nome')),
                ('celular', models.CharField(help_text='Informe o telefone Ex.:(xx)xxxxx-xxxx', max_length=14, verbose_name='Celular')),
                ('email', models.EmailField(help_text='Informe o email', max_length=100, verbose_name='Email')),
                ('foto', stdimage.models.StdImageField(upload_to='corretores', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Informe a descrição do imóvel', max_length=35, verbose_name='Descrição')),
                ('foto', stdimage.models.StdImageField(upload_to='fotos', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=35, verbose_name='Nome')),
                ('celular', models.CharField(help_text='Informe o telefone Ex.:(xx)xxxxx-xxxx', max_length=16, verbose_name='Celular')),
                ('email', models.EmailField(help_text='Informe o email', max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Informe a status do imóvel', max_length=35, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Informe a descrição do imóvel', max_length=35, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e hora da visita', verbose_name='Data e Hora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente', verbose_name='Cliente')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.corretor', verbose_name='Corretor')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código do imóvel', max_length=7, unique=True, verbose_name='Codigo')),
                ('endereco', models.CharField(help_text='Informe o endereço', max_length=100, verbose_name='Endereço')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Informe o Valor do Imóvel', max_digits=10, verbose_name='Valor')),
                ('iptu', models.DecimalField(decimal_places=2, help_text='Informe o IPTU', max_digits=10, verbose_name='IPTU')),
                ('condominio', models.DecimalField(decimal_places=2, help_text='Informe o valor do condominio', max_digits=5, verbose_name='Condomínio')),
                ('area_total', models.DecimalField(decimal_places=2, help_text='Informe a área total do imóvel', max_digits=5, verbose_name='Área Total')),
                ('descricao', models.CharField(help_text='Descrição do Imóvel', max_length=14, verbose_name='Descrição')),
                ('quarto', models.DecimalField(decimal_places=2, help_text='Quantidade de quartos', max_digits=5, verbose_name='Quartos')),
                ('banheiro', models.DecimalField(decimal_places=2, help_text='Quantidade de banheiros', max_digits=5, verbose_name='Banheiros')),
                ('garagem', models.DecimalField(decimal_places=2, help_text='Vagas na Garagem', max_digits=5, verbose_name='Garagem')),
                ('caracteristica', models.ManyToManyField(to='agenda.Caracteristicas')),
                ('comodidade', models.ManyToManyField(to='agenda.Comodidades')),
                ('proprietario', models.ManyToManyField(to='agenda.Proprietario')),
                ('statu', models.ManyToManyField(to='agenda.Status')),
                ('tipo', models.ManyToManyField(to='agenda.Tipos')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
